version: '3'
services: 
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - '3050:80'
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./server:/app
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./frontend:/app
  tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./frontend:/app
    command: ["npm", "run", "test"]
  