
export const GET_ALL_REPORTS = "GET_ALL_REPORTS";
export const GET_ALL_REPORTS_SUCCESS = "GET_ALL_REPORTS_SUCCESS";
export const GET_ALL_REPORTS_FAIL = "GET_ALL_REPORTS_FAIL";


export const RESOLVE_REPORT = "RESOLVE_REPORT";
export const RESOLVE_REPORT_SUCCESS = "RESOLVE_REPORT_SUCCESS";
export const RESOLVE_REPORT_FAIL = "RESOLVE_REPORT_FAIL";


export const BLOCK_REPORT = "BLOCK_REPORT";
export const BLOCK_REPORT_SUCCESS = "BLOCK_REPORT_SUCCESS";
export const BLOCK_REPORT_FAIL = "BLOCK_REPORT_FAIL";


